name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://example.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Typecheck TypeScript
        run: yarn run tsc --noEmit

      - name: Lint
        run: yarn run lint
